### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by WaterSpout** [SerafimArts/Asset#4]
Здравствуйте.

При обработке исключений, например:
```php
throw new FileNotFoundException(sprintf($messageNotFound, [$fpath]))
```
выскакивает ошибка
```php
Array to string conversion
```

Предлагаю заменить sprintf на vsprintf

**Comment by SerafimArts** [comment]
Не, там просто опечатка, sprintf принимает в качестве 2+ аргументов вариадик, а не массив. Просто квадратные скобки убрать.

**Comment by SerafimArts** [comment]
Fixed (commit): https://github.com/SerafimArts/Asset/commit/6c48b9c10058568c84cf1cd79c782a88d3c4f4a0
Release: https://github.com/SerafimArts/Asset/releases/tag/2.1.3
