### ISSUE TITLE
compress image

### ISSUE THREAD

**Issue by WaterSpout** [SerafimArts/Asset#5]
Правильно ли я понимаю, что для картинок, например: `asset_file('test.jpeg')` или ```php asset_link('test.jpeg') ``` не происходит сжатия, как для css и js файлов? Поэксперементировал с картинкой размером 594Кб, после создания asset файла в public/assets, размер не изменился.
Если такого сжатия нет, тогда какая целесообразность использовать asset картинок?

**Comment by SerafimArts** [comment]
пока никакой =) Просто есть такая возможность. В теории, на перспективу, хотел сделать чейнинг, вида:
```
asset_link('test.jpg')->size(100, 100)->rotate(90)
```
После должно генерировать нужную картинку и отправлять в публичную директорию, т.е. с кешем результата. Но пока руки не добрались.

**Comment by WaterSpout** [comment]
Спасибо, за разъяснения.
